version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      production:
        dependency-type: "production"
      development:
        dependency-type: "development"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
