version: 2
updates:
  - package-ecosystem: npm
    directory: /
    groups:
      npm:
        patterns: ["*"]
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
