name: Slickybot CI

on:
  pull_request:
    branches: [main]
    types: [opened, edited, reopened, synchronize]

jobs:
  build:
    name: Docker Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e
      - name: Docker Build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a
        with:
          platforms: ${{ matrix.platform }}
          push: false

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version-file: package.json
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Unit Tests
        run: npm run test:coverage
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          output: both
          thresholds: '60 80'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Validate PR title with commitlint
        uses: kevintyj/prlint@4f01874a73c0cda0c42d6226f89c0a32db80a497

  ci:
    name: SlickyBot CI
    if: always()
    needs:
      - build
      - test
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Check Jobs Succeeded
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35
        with:
          jobs: ${{ toJSON(needs) }}
