name: Dependabot auto-merge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'SlickyCorp-Heavy-Manufacturing/SlickBot'
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --body "" --merge --subject "$PR_TITLE" "$PR_URL"
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.AUTOMERGE_PAT }}
