#!/usr/bin/env python3
"""Generate src/pieces.inc : the 7 tetromino shapes (themed Sega components)
as 4x4 bitmasks, four rotations each, packed into 16-bit little-endian words.

Bit layout: bit (r*4 + c) set means cell (row r, col c) is filled, with
bit 0 = top-left of the 4x4 box.
"""

import sys

# spawn orientations (4 rows x 4 cols)
SHAPES = {
    'I': ['....',
          '####',
          '....',
          '....'],
    'O': ['....',
          '.##.',
          '.##.',
          '....'],
    'T': ['....',
          '###.',
          '.#..',
          '....'],
    'S': ['....',
          '.##.',
          '##..',
          '....'],
    'Z': ['....',
          '##..',
          '.##.',
          '....'],
    'J': ['....',
          '#...',
          '###.',
          '....'],
    'L': ['....',
          '..#.',
          '###.',
          '....'],
}

ORDER = ['I', 'O', 'T', 'S', 'Z', 'J', 'L']

# sprite palette (0-3) used to colour each falling piece
PAL = {'I': 1, 'O': 2, 'T': 3, 'S': 0, 'Z': 1, 'J': 2, 'L': 3}


def rot_cw(grid):
    # rotate a 4x4 grid clockwise
    return [''.join(grid[3 - c][r] for c in range(4)) for r in range(4)]


def mask(grid):
    m = 0
    for r in range(4):
        for c in range(4):
            if grid[r][c] == '#':
                m |= 1 << (r * 4 + c)
    return m


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else 'pieces.inc'
    lo, hi, pal = [], [], []
    for name in ORDER:
        g = SHAPES[name]
        for _ in range(4):
            m = mask(g)
            lo.append(m & 0xFF)
            hi.append((m >> 8) & 0xFF)
            g = rot_cw(g)
        pal.append(PAL[name])

    def emit(fh, label, vals):
        fh.write(f'{label}:\n')
        for i in range(0, len(vals), 8):
            chunk = ', '.join(f'${v:02X}' for v in vals[i:i + 8])
            fh.write(f'    .byte {chunk}\n')

    with open(out, 'w') as fh:
        fh.write('; AUTO-GENERATED by tools/gen_pieces.py -- do not edit.\n')
        fh.write('NUM_PIECES = 7\n\n')
        emit(fh, 'piece_lo', lo)     # indexed [piece*4 + rot]
        emit(fh, 'piece_hi', hi)
        emit(fh, 'piece_pal', pal)   # indexed [piece]
    print(f'wrote {out}: {len(ORDER)} pieces x 4 rotations')


if __name__ == '__main__':
    main()
