#!/usr/bin/env python3
"""Generate src/music.inc : NES APU period tables + an ORIGINAL jazzy song.

The tune is a smooth lounge-jazz loop (ii-V-I-vi in C: Dm7 - G7 - Cmaj7 - Am7)
with a walking triangle bass, comped pulse harmony and brushed noise drums.
It is an original composition written to evoke a cosy sitcom-jazz mood -- it is
NOT a transcription of any existing theme.
"""

import sys

CPU = 1789773.0  # NTSC CPU clock

SEMI = {'C': 0, 'C#': 1, 'D': 2, 'D#': 3, 'E': 4, 'F': 5,
        'F#': 6, 'G': 7, 'G#': 8, 'A': 9, 'A#': 10, 'B': 11}

REST = 0xFF   # note off (silence channel)
HOLD = 0xFE   # sustain previous note (no retrigger)


def idx(name):
    """'C2' -> 0, 'A4' -> 33 ... (C2 == index 0)."""
    if name in ('R', None):
        return REST
    if name == '-':
        return HOLD
    note = name[:-1]
    octave = int(name[-1])
    return (octave - 2) * 12 + SEMI[note]


def freq(i):
    # MIDI number of index 0 (C2) is 36.
    midi = 36 + i
    return 440.0 * (2.0 ** ((midi - 69) / 12.0))


def build_tables(n):
    plo, phi, tlo, thi = [], [], [], []
    for i in range(n):
        f = freq(i)
        p = int(round(CPU / (16.0 * f))) - 1          # pulse timer
        t = int(round(CPU / (32.0 * f))) - 1          # triangle timer
        p = max(0, min(2047, p))
        t = max(0, min(2047, t))
        plo.append(p & 0xFF); phi.append((p >> 8) & 0x07)
        tlo.append(t & 0xFF); thi.append((t >> 8) & 0x07)
    return plo, phi, tlo, thi


N = 49  # C2..C6

# --- the song, 4 bars x 8 eighth-notes -------------------------------------
mel = ['F4', 'R', 'A4', 'C5', 'R', 'A4', 'F4', 'R',      # Dm7
       'B4', 'R', 'D5', 'R', 'B4', 'A4', 'G4', 'R',      # G7
       'E4', 'G4', 'B4', 'C5', 'R', 'B4', 'G4', 'R',     # Cmaj7
       'C5', 'B4', 'A4', 'G4', 'E4', 'R', 'G4', 'R']     # Am7

harm = ['R', 'F4', 'R', 'A4', 'R', 'C5', 'R', 'A4',
        'R', 'B4', 'R', 'F4', 'R', 'B4', 'R', 'F4',
        'R', 'E4', 'R', 'B4', 'R', 'E4', 'R', 'B4',
        'R', 'C5', 'R', 'G4', 'R', 'C5', 'R', 'G4']

bass = ['D2', '-', 'A2', '-', 'D3', '-', 'F3', '-',
        'G2', '-', 'D3', '-', 'G3', '-', 'F3', '-',
        'C2', '-', 'G2', '-', 'C3', '-', 'E3', '-',
        'A2', '-', 'E3', '-', 'A3', '-', 'G3', '-']

# percussion: 1 = hat, 2 = snare, 0 = none
perc = [1, 1, 2, 1, 1, 1, 2, 1] * 4


def emit_bytes(fh, label, vals):
    fh.write(f'{label}:\n')
    for i in range(0, len(vals), 8):
        chunk = ', '.join(f'${v & 0xFF:02X}' for v in vals[i:i + 8])
        fh.write(f'    .byte {chunk}\n')


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else 'music.inc'
    plo, phi, tlo, thi = build_tables(N)
    with open(out, 'w') as fh:
        fh.write('; AUTO-GENERATED by tools/gen_music.py -- do not edit.\n')
        fh.write(f'SONG_LEN = {len(mel)}\n')
        fh.write(f'NOTE_REST = ${REST:02X}\n')
        fh.write(f'NOTE_HOLD = ${HOLD:02X}\n\n')
        emit_bytes(fh, 'pulse_lo', plo)
        emit_bytes(fh, 'pulse_hi', phi)
        emit_bytes(fh, 'tri_lo', tlo)
        emit_bytes(fh, 'tri_hi', thi)
        fh.write('\n')
        emit_bytes(fh, 'song_mel', [idx(x) for x in mel])
        emit_bytes(fh, 'song_harm', [idx(x) for x in harm])
        emit_bytes(fh, 'song_bass', [idx(x) for x in bass])
        emit_bytes(fh, 'song_perc', perc)
    print(f'wrote {out}: {len(mel)} steps, {N} notes')


if __name__ == '__main__':
    main()
